services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
    env_file:
      - .env
    volumes:
      - ./.env:/home/python/.env:ro
      - ./logs:/home/python/logs
    networks:
      - setpilot-net
    restart: unless-stopped

networks:
  setpilot-net:
    external: true
