FROM python:3.12-bookworm

ENV LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/home/python/.local/bin:${PATH}"

RUN apt-get update -qq && \
    apt-get install -y \
      curl \
      git \
      net-tools \
      procps \
      sudo \
      vim \
      && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

ARG USERNAME=python
ARG USER_UID=1001
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /home/python/app
COPY . /home/python/app

RUN chown -R $USERNAME:$USERNAME /home/python

USER $USERNAME

CMD ["/bin/bash"]
