FROM golang:1.27-bookworm

ENV LANG=C.UTF-8

RUN apt-get update -qq && \
    apt-get install -y \
      curl \
      git \
      net-tools \
      procps \
      sudo \
      vim \
      && rm -rf /var/lib/apt/lists/*

ARG USERNAME=bot
ARG USER_UID=1001
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /home/bot
COPY . /home/bot

RUN chown -R $USERNAME:$USERNAME /home/bot

USER $USERNAME

CMD ["/bin/bash"]
